// Action Types
export const LOG_IN = 'LOG_IN';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAIL = 'LOG_IN_FAIL';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const LOAD_DASHBOARD = 'LOAD_DASHBOARD';
export const LOAD_DASHBOARD_SUCCESS = 'LOAD_DASHBOARD_SUCCESS';
export const LOAD_DASHBOARD_FAIL = 'LOAD_DASHBOARD_FAIL';

export const LOAD_USER_LIST = 'LOAD_USER_LIST';
export const LOAD_USER_LIST_SUCCESS = 'LOAD_USER_LIST_SUCCESS';
export const LOAD_USER_LIST_FAIL = 'LOAD_USER_LIST_FAIL';

export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';
export const CREATE_NEW_USER_FAIL = 'CREATE_NEW_USER_FAIL';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const EDIT_ROOM = 'EDIT_ROOM';
export const EDIT_ROOM_SUCCESS = 'EDIT_ROOM_SUCCESS';
export const EDIT_ROOM_FAIL = 'EDIT_ROOM_FAIL';
export const CREATE_NEW_ROOM_FAIL = 'CREATE_NEW_ROOM_FAIL';
export const DELETE_ROOM_FAIL = 'DELETE_ROOM_FAIL';

export const LOAD_ROOM_LIST = 'LOAD_ROOM_LIST';
export const LOAD_ROOM_LIST_SUCCESS = 'LOAD_ROOM_LIST_SUCCESS';
export const LOAD_ROOM_LIST_FAIL = 'LOAD_ROOM_LIST_FAIL';

export const EDIT_CLASS = 'EDIT_CLASS';
export const EDIT_CLASS_SUCCESS = 'EDIT_CLASS_SUCCESS';
export const EDIT_CLASS_FAIL = 'EDIT_CLASS_FAIL';
export const CREATE_NEW_CLASS_FAIL = 'CREATE_NEW_CLASS_FAIL';
export const DELETE_CLASS_FAIL = 'DELETE_CLASS_FAIL';

export const LOAD_CLASS_LIST = 'LOAD_CLASS_LIST';
export const LOAD_CLASS_LIST_SUCCESS = 'LOAD_CLASS_LIST_SUCCESS';
export const LOAD_CLASS_LIST_FAIL = 'LOAD_CLASS_LIST_FAIL';

export const GET_ALL_CLASS_BY_USER = 'GET_ALL_CLASS_BY_USER';
export const GET_ALL_CLASS_BY_USER_SUCCESS = 'GET_ALL_CLASS_BY_USER_SUCCESS';
export const GET_ALL_CLASS_BY_USER_FAIL = 'GET_ALL_CLASS_BY_USER_FAIL';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAIL = 'UPDATE_USER_INFO_FAIL';

export const LOG_OUT = 'LOG_OUT';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAIL = 'LOG_OUT_FAIL';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';

export const HIDE_ALL_USER_MODAL = 'HIDE_ALL_USER_MODAL';
export const OPEN_EDIT_USER_MODAL = 'OPEN_EDIT_USER_MODAL';
export const OPEN_CREATE_USER_MODAL = 'OPEN_CREATE_USER_MODAL';

export const HIDE_ALL_CLASS_MODAL = 'HIDE_ALL_CLASS_MODAL';
export const OPEN_EDIT_CLASS_MODAL = 'OPEN_EDIT_CLASS_MODAL';
export const OPEN_CREATE_CLASS_MODAL = 'OPEN_CREATE_CLASS_MODAL';

export const HIDE_ALL_ROOM_MODAL = 'HIDE_ALL_ROOM_MODAL';
export const OPEN_EDIT_ROOM_MODAL = 'OPEN_EDIT_ROOM_MODAL';
export const OPEN_CREATE_ROOM_MODAL = 'OPEN_CREATE_ROOM_MODAL';

// API
export const BASE_URL = process.env.BASE_URL || 'http://localhost:4000';
export const SIGNIN_ENDPOINT = '/auth/login';
export const USER_INFO_ENDPOINT = '/api/me';
export const USERS_ENDPOINT = '/api/users';
export const ROOMS_ENDPOINT = '/api/rooms';
export const CLASSES_ENDPOINT = '/api/classes';